version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "14.0.0"  # Specify the Xcode version
    working_directory: ~/project

jobs:
  build:
    executor: macos-executor
    steps:
      - checkout  # Pull down the code

      - run:
          name: test1
          command: |
              curl -O https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_720p_h264.mov
              ls
              brew --version
              node --version
              python --version
              brew install ffmpeg
              ffmpeg -version

      - run:
          name: Build the project
          command: |
              mkdir -p output
              ffmpeg -i big_buck_bunny_720p_h264.mov -vf "fps=2,crop=300:200:100:100,scale=640:480" output/output_%03d.png

      - run:
          name: Run tests
          command: pip list

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

