name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: flyci-macos-14-m2

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'  # Optional: Use pip cache for dependencies

      # Install the packages directly
      - run: pip install --pre torch cloudinary==1.40.0 numpy==1.26.4 \
             opencv-python-headless opencv-contrib-python-headless \
             fasttext-langdetect==1.0.5 googlesearch-python==1.2.4 \
             boto3 easyocr alive_progress==3.1.5 \
             --extra-index-url https://download.pytorch.org/whl/nightly/cpu
      
      - name: Print python packages
        run: pip list
      
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runner's shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Print python on mac
        run: |
          python --version
          pip list
          sw_vers -productVersion
          system_profiler SPSoftwareDataType
          sysctl -n hw.ncpu
          system_profiler SPHardwareDataType

      # - name: test
      #   run: |
      #     pip install torch
      #     pip list

      - name: test2
        run: |
          curl -O https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_720p_h264.mov
          ls
          brew --version
          node --version
          python --version
          brew install ffmpeg
          ffmpeg -version

      - name: test3
        run: |
          mkdir -p output
          ffmpeg -i big_buck_bunny_720p_h264.mov -vf "fps=2,crop=300:200:100:100,scale=640:480" output/output_%03d.png


